config/routes.rb
Rails.application.routes.draw do

  resources :banks

  resources :categories do
    resources :sub_categories
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticated :user do
    root to: 'home#dashboard', as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users
  get 'home/index'

end

app/models/bank.rb
class Bank
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  validates_presence_of :name

end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show]
  before_action :authenticate_user!

  # GET /banks
  # GET /banks.json
  def index
    @banks = Bank.all
  end

  # GET /banks/1
  # GET /banks/1.json
  def show
  end

  # GET /banks/new
  # def new
  #   @bank = Bank.new
  # end

  # # GET /banks/1/edit
  # def edit
  # end

  # # POST /banks
  # # POST /banks.json
  # def create
  #   @bank = Bank.new(bank_params)

  #   respond_to do |format|
  #     if @bank.save
  #       format.html { redirect_to @bank, notice: 'Bank was successfully created.' }
  #       format.json { render action: 'show', status: :created, location: @bank }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @bank.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /banks/1
  # # PATCH/PUT /banks/1.json
  # def update
  #   respond_to do |format|
  #     if @bank.update(bank_params)
  #       format.html { redirect_to @bank, notice: 'Bank was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @bank.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /banks/1
  # # DELETE /banks/1.json
  # def destroy
  #   @bank.destroy
  #   respond_to do |format|
  #     format.html { redirect_to banks_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:name)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_form.html.erb
<%= simple_form_for(@bank) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :parsers %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/banks/index.html.erb
<%- model_class = Bank -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
    </tr>
  </thead>
  <tbody>
    <% @banks.each do |bank| %>
      <tr>
        <td><%= link_to bank.name, bank_path(bank.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/banks/show.html.erb
<%- model_class = Bank -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong>
  <%= @bank.name %>
</p>


<%= link_to t('.back', :default => t("helpers.links.back")),
            categories_path, :class => 'btn btn-mini' %>