config/routes.rb
Rails.application.routes.draw do

  resources :banks

  resources :categories do
    resources :sub_categories
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticated :user do
    root to: 'home#dashboard', as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users
  get 'home/index'

end

app/models/category.rb
class Category
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Enum

  field :name, type: String
  enum :group, [:unclassified, :transfer, :split, :income, :expense]
  field :sub_categories, type: Array, default: []

  embeds_many :sub_categories
  # has_many :transactions

  validates_presence_of :name, :group
  attr_accessor :type_description

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all().asc(:group,:name)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :type)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:sub_categories) %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.type_description %></td>
        <td><%= link_to category.name, category_path(category.id) %></td>
        <td>
          [<%= link_to "Todas", category_sub_categories_path(category.id) %>] - <%= category.sub_categories.sort_by{|e| e.name}.map{|p| p.name}.join(", ") %>.
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong>
  <%= @category.name %>
</p>

<p>
  <strong><%= model_class.human_attribute_name(:type_description) %>:</strong>
  <%= @category.type_description %>
</p>

<p>
  <strong><%= model_class.human_attribute_name(:sub_categories) %>:</strong>
  <%= raw(@category.sub_categories.sort_by{|e| e.name}.map{|p| link_to p.name, category_sub_category_path(@category,p.id)}.join(", ")) %>.

</p>

<%= link_to t('.back', :default => t("helpers.links.back")),
            categories_path, :class => 'btn btn-mini' %>