config/routes.rb
Rails.application.routes.draw do

  resources :banks

  resources :categories do
    resources :sub_categories
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticated :user do
    root to: 'home#dashboard', as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index"
  end

  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users
  get 'home/index'

end

app/views/layouts/_footer.html.erb
<p>Copyright &copy; 2015 Daniel Ambrosio </p>
<p>Versão <%= `git rev-parse HEAD` %>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Numis", root_path, :class => 'navbar-brand' %>
    </div><!-- /.navbar-header -->

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li class="<%= 'active' if params[:controller].downcase() == 'banks' %>"> <%= link_to "Bancos", banks_path %> </li>
          <li class="<%= 'active' if params[:controller].downcase() == 'categories' %>"> <%= link_to "Categorias", categories_path %> </li>

          <% if current_user.has_role? :admin %>
            <li><%= link_to 'Admin', users_path %></li>
          <% end %>
        <% else %>
        <% end %>

      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="<%= 'active' if params[:controller].downcase() == 'users/registrations' %>"> <%= link_to 'Minha Conta', edit_user_registration_path %> </li>
        <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
      <% else %>
        <li><%= link_to 'Cadastrar', new_user_registration_path %></li>
        <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!-- EXEMPLOS -->
<% if false %>

<%= params[:controller] %>
<%= debug params %>
<li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
<li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>

<ul class="nav">
  <li class="<%= 'active' if params[:controller] == 'controller1' %>"> <a href="/link">Link</a> </li>
  <li class="<%= 'active' if params[:controller] == 'controller2' %>"> <a href="/link">Link</a> </li>
  <li class="<%= 'active' if params[:controller] == 'controller3' %>"> <a href="/link">Link</a> </li>
</ul>

<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">Separated link</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">One more separated link</a></li>
  </ul>
</li>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Numis.com.br" %>">
    <meta name="author" content="Daniel Rodrigues Ambrosio">
    <link rel="icon" href="../../favicon.ico">

    <title><%= content_for?(:title) ? "Numis - " + yield(:title) : "Numis.com.br" %></title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>

  <body role="document" class="<%= controller_name %> <%= action_name %>">

  <%= render 'layouts/navigation' %>

  <div id="main" role="main">
    <div class="container">
      <div class="content">
         <div class="row">
          <div class="span12">
            <%= render partial: 'layouts/messages', flash: flash %>
            <%= yield %>
          </div>
        </div>
      </div>
    </div> <!--! end of .container -->
  </div> <!--! end of #main -->

    <footer class="footer">
      <div class="container">
        <ul class="footer-links">
          <li><a href="http://geekpride.com.br">Blog Geek Pride</a></li>
          <li class="muted">·</li>
          <li><a href="https://github.com/daniambrosio/numis">Numis@Github</a></li>
          <li class="muted">·</li>
          <li><a href="https://github.com/daniambrosio/rails4-bootstrap-devise-cancan-omniauth-railsadmin">Rails4 Base App</a></li>
        </ul>
        <%= render 'layouts/footer' %>
      </div>
    </footer>

  </body>
</html>